backend:
  name: git-gateway
branch: master
media_folder: static/img
public_folder: /img
collections:
  -name: "blog"
  -folder: "src/blog"
	-fields:		 
    -label: "Title"
	  name: "title"
		widget: "string"	
		
	

